### ISSUE TITLE
About the prob_threshold in dtu_eval.sh

### ISSUE THREAD

**Issue by aweijx** [TruongKhang/cds-mvsnet#2]
Hi, thanks for sharing the code!
I can't find your prob_threshold settings in dtu_eval.sh, can you provide them?

Looking forward to your reply.
Many Thanks!!!

**Comment by TruongKhang** [comment]
Hi @aweijx, for DTU, we didn't need a `prob_threshold` because the fusion method (`fusibile`) worked well for noise filtering. Therefore, I used a default value of 0.0. You can find this in file test.py with the argument `--prob_threshold`.

You can change this setting by yourself but the results might be different.

**Comment by aweijx** [comment]
> Hi @aweijx, for DTU, we didn't need a `prob_threshold` because we find that the fusion method (`fusibile`) worked well for noise filtering. Therefore, I used a default value of 0.0. You can find this in file test.py with the argument `--prob_threshold`.
> 
> You can change this setting by yourself but the results might be different.

Thank you for your kind and fast reply!
